### ISSUE TITLE
import/no-extraneous-dependencies

### ISSUE THREAD

**Issue by bea-pl** [ApiTreeCZ/toolbox#2]
error  '@nestjs/testing' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
error  'vitest' should be listed in the project's dependencies, not devDependencies           import/no-extraneous-dependencies

https://github.com/ApiTreeCZ/sc20-portal/pull/8

**Comment by rozsival** [comment]
Please, move the test files to `/tests` folder, they should not be in `/src`. Then, this rule will work correctly.
